### ISSUE TITLE
Reset competition data

### ISSUE THREAD

**Issue by ThinkRedstone** [FirstLegoLeague/Launcher#28]
I suggest having a button with a confirmation dialog that deletes the `modules/scoring/data` directory. This will not reset the passwords, but it will delete all the settings specified in fllscoring, and all of the scores; which I believe is all the competition data.

**Comment by idanstark42** [comment]
That sounds good. Do you think we can make it configurable, so that each module can have an attribute to specify which path (s) to delete, so that the only place the launcher is aware of the modules is still in modules.yml?

**Comment by ThinkRedstone** [comment]
We can, and I think I'll even expand that to also support a resetScript property

**Comment by idanstark42** [comment]
Sounds even better

**Comment by ThinkRedstone** [comment]
Fixed by #29
