### ISSUE TITLE
add exectubles to the releases page on GitHub

### ISSUE THREAD

**Issue by kmeesters** [FirstLegoLeague/Launcher#40]
Hi!

Not really a bug, but a request. Can you add the executalbes (result from the builds) to the 'releases' of this GitHub repository? That way we have all downloads / code / etc in one place. Added bonus is that we can also track downloads, and quickly update with new versions (in the future even have built-in feature that check if the software is the latest version). This way we can also ensure we provide one link, and that everyone will always grab the right version.

fll-tools.com can then serve as a frontend (as we have done for the scoring software here: http://www.fll-tools.com/software/scoring/ (although we need to update the site in general).

Reason for asking this: I have some people who want to test it (locally on their own pcs, not at events yet), and want to make sure we are distributing one link that will keep working. For more info: https://github.com/FirstLegoLeague/Launcher/releases

**Comment by idanstark42** [comment]
Sorry, accidentally closed and reopened. I'll do it tonight, I think it's a great idea

**Comment by idanstark42** [comment]
Done
